displayName: crossover-limiter
type: middleware
iconPath: .assets/icon.png

import: github.com/kotalco/crossover-limiter

summary: "RESP powered rate limiter middleware for Traefik"

testData:
  #pattern used to extract the requestId from the urlPath
  RequestIdPattern: "([a-z0-9]{42})"
  #RedisAddress storage address
  RedisAddress: "localhost:6379"
  #RedisAuth to authenticate redis storage
  RedisAuth: "123456"
  #RedisPoolSize number of open connections
  RedisPoolSize: 10
